table Trabajadores
	lineageTag: 600743cc-dc9a-4a4a-bc21-700ccf1ab9cc

	column cttrabajador
		dataType: int64
		formatString: 0
		lineageTag: f5201701-a038-4828-a068-2e0bacfb2c1c
		summarizeBy: none
		sourceColumn: cttrabajador

		annotation SummarizationSetBy = Automatic

	column trsexo
		dataType: string
		lineageTag: 98b86b05-6fa8-42c3-82cd-67572a80d417
		summarizeBy: none
		sourceColumn: trsexo

		annotation SummarizationSetBy = Automatic

	column trfechanac
		dataType: dateTime
		formatString: Long Date
		lineageTag: 502755f8-646e-4f29-8ab5-fbbeca74e79c
		summarizeBy: none
		sourceColumn: trfechanac

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column trnacionalidad
		dataType: string
		lineageTag: 1ea04f0b-45f8-406e-9dbe-1d1e9017ed80
		summarizeBy: none
		sourceColumn: trnacionalidad

		annotation SummarizationSetBy = Automatic

	column Años
		dataType: double
		lineageTag: cb0ecd05-75ec-422c-b8c1-85110a67ae7b
		summarizeBy: none
		sourceColumn: Años

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trdiscapacidad
		dataType: int64
		formatString: 0
		lineageTag: 5bd5453c-ee71-498b-af6c-cf1da7f66c33
		summarizeBy: none
		sourceColumn: trdiscapacidad

		annotation SummarizationSetBy = Automatic

	column trnombrecompleto
		dataType: string
		lineageTag: 1a4cf512-ee8a-488b-846c-4df53c8c26f5
		summarizeBy: none
		sourceColumn: trnombrecompleto

		annotation SummarizationSetBy = Automatic

	column Telefono
		dataType: string
		lineageTag: 1fc6742b-5a08-4226-9bbb-46d03f73175c
		summarizeBy: none
		sourceColumn: Telefono

		annotation SummarizationSetBy = Automatic

	column tremail
		dataType: string
		lineageTag: 9f4ac0a6-6481-4988-aa0f-6f392f49b64f
		summarizeBy: none
		sourceColumn: tremail

		annotation SummarizationSetBy = Automatic

	partition Trabajadores-20b406c8-64f1-49f8-8a8a-4cfb55f7682d = m
		mode: import
		source =
				let
				    Source = Sql.Database("10.10.138.5\TEMPORING", "no3001", [Query="SELECT DISTINCT#(lf)    contra.cttrabajador,#(lf)    trnombrecompleto,#(lf)    CASE#(lf)        WHEN trabajador.trtelefmovil IS NOT NULL#(lf)             AND LTRIM(RTRIM(trabajador.trtelefmovil)) <> ''#(lf)             AND LEFT(LTRIM(RTRIM(trabajador.trtelefmovil)), 1) IN ('6','7')#(lf)            THEN LTRIM(RTRIM(trabajador.trtelefmovil))#(lf)        WHEN trabajador.trtelefono IS NOT NULL#(lf)             AND LTRIM(RTRIM(trabajador.trtelefono)) <> ''#(lf)             AND LEFT(LTRIM(RTRIM(trabajador.trtelefono)), 1) IN ('6','7')#(lf)            THEN LTRIM(RTRIM(trabajador.trtelefono))#(lf)        ELSE NULL#(lf)    END AS Telefono,#(lf)#(tab)trabajador.tremail,#(lf)    trabajador.trsexo,#(lf)    trabajador.trfechanac,#(lf)    trabajador.trnacionalidad,#(lf)    ((CONVERT(decimal(10,2), (GETDATE() - trabajador.trfechanac)))) / 365 AS Años,#(lf)    trdiscapacidad#(lf)FROM contra#(lf)INNER JOIN trabajador#(lf)    ON contra.ctempresa = trabajador.trempresa#(lf)   AND contra.cttrabajador = trabajador.trtrabajador#(lf)INNER JOIN centros#(lf)    ON contra.ctempresa = centros.ceempresa#(lf)   AND contra.ctcentro = centros.cecentro#(lf)WHERE ctempresa = 01#(lf)  AND (contra.ctfechafinreal IS NULL OR YEAR(contra.ctfechafinreal) >= 2023)"]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"trfechanac", type date}, {"trdiscapacidad", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

